### ISSUE TITLE
TK05 : TESTING 

### ISSUE THREAD

**Issue by FacKuSalvatierra** [FacKuSalvatierra/CBA-FLY-APP#15]
Planificar 3 casos de prueba para la app a desarrollar en el proyecto, de acuerdo a lo sugerido. Dejar registro dentro de una nueva pagina de la WIKI, denominada testing (Uds deciden si lo hacen sobre el mismo archivo md o linkean un google docs, sheet)

**Comment by FacKuSalvatierra** [comment]
El Proceso de Prueba Ejemplo
En la Norma ISO/IEC/IEEE 29119 define para cada caso de prueba debe haber:

- Un identificador único

-  Un objetivo, que se va a probar

- Una prioridad, orden en el que se ejecutará según importancia

- Trazabilidad, pasos a seguir para ejecutar el caso de prueba

-  Precondiciones que deben cumplirse antes del caso de prueba

-  Entradas, datos con los que se va a probar

- Resultados Esperados, en base a lo planificado, que resultado se espera

- Resultados

**Comment by CodeAgua** [comment]
I did it!
