### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by FacKuSalvatierra** [FacKuSalvatierra/CBA-FLY-APP#3]
Se tiene que actualizar el UML agregando la versión móvil

**Comment by FacKuSalvatierra** [comment]
Diseño de software
Es el proceso de definición de la arquitectura, componentes, interfaces y otras características de un sistema o componente que resulta de este proceso.
En la fase de Diseño se crea una solución a nivel lógico para satisfacer los requisitos, basándose en el conocimiento reunido en la fase de análisis.

Las tareas que se realizan en esta fase son las siguientes:

Definir el Diagrama de Clases de Diseño detallado.
Definir las estructuras de datos necesarias para almacenar la información que utiliza el sistema.
Definir la Interfaz de Usuario e Informes.
¿Por qué implementar con UML?
El Lenguaje Unificado de Modelado (UML) desempeña un rol muy relevante, no sólo en el desarrollo de software, sino también en otros tipos de procedimientos de muchas industrias, ya que es una forma de mostrar visualmente el comportamiento y la estructura de un sistema o procesos empresariales.  


¿Cuáles son las ventajas del UML? 
Simplifica las complejidades 
Mantiene abiertas las líneas de comunicación 
Automatiza la producción de software y los procesos  
Ayuda a resolver los problemas arquitectónicos constantes 
Aumenta la calidad del trabajo 
Reduce los costos y el tiempo de comercialización 
Existen dos tipos principales de diagramas UML: diagramas de estructura y diagramas de comportamiento (y dentro de esas categorías se encuentran varios otros). Estas variaciones existen para representar los numerosos tipos de escenarios y diagramas que usan los diferentes tipos de personas. 

Fuente de información https://diagramasuml.com/

**Comment by eliasgiannantonio** [comment]
![UML-CBAFLY-APP](https://github.com/FacKuSalvatierra/CBA-FLY-APP/assets/105678923/dfb28870-9a4b-46ac-93f1-d2afeea24419)
Agregado el esquema UML en la carpeta de documentación correspondiente.
